// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseKeeping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250814161504_addingAdmin")]
    partial class addingAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseKeeping.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HouseKeeping.Models.DailyJobEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HousekeeperId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HousekeeperId");

                    b.ToTable("DailyJobEntries");
                });

            modelBuilder.Entity("HouseKeeping.Models.Housekeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Housekeepers");
                });

            modelBuilder.Entity("HouseKeeping.Models.DailyJobEntry", b =>
                {
                    b.HasOne("HouseKeeping.Models.Housekeeper", "Housekeeper")
                        .WithMany("JobEntries")
                        .HasForeignKey("HousekeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Housekeeper");
                });

            modelBuilder.Entity("HouseKeeping.Models.Housekeeper", b =>
                {
                    b.Navigation("JobEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
